version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_AR"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "prueba.skoll.ar"
      traefik.enable: "true"
      traefik.domain: "prueba.skoll.ar"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:prueba.skoll.ar;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host:prueba.skoll.ar
      traefik.longpolling-0.frontend.rule: Host:prueba.skoll.ar;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.prueba-15-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.prueba-15-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.prueba-15-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.prueba-15-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.prueba-15-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.prueba-15-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.prueba-15-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.prueba-15-0-prod-main-0.rule: Host(`prueba.skoll.ar`)
      traefik.http.routers.prueba-15-0-prod-main-0.service: prueba-15-0-prod-main
      traefik.http.routers.prueba-15-0-prod-main-0.middlewares:
        prueba-15-0-prod-buffering, prueba-15-0-prod-compress,
        prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-main-secure-0.rule: Host(`prueba.skoll.ar`)
      traefik.http.routers.prueba-15-0-prod-main-secure-0.service: prueba-15-0-prod-main
      traefik.http.routers.prueba-15-0-prod-main-secure-0.middlewares:
        prueba-15-0-prod-buffering, prueba-15-0-prod-compress,
        prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.prueba-15-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.prueba-15-0-prod-longpolling-0.rule:
        Host(`prueba.skoll.ar`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.prueba-15-0-prod-longpolling-0.service: prueba-15-0-prod-longpolling
      traefik.http.routers.prueba-15-0-prod-longpolling-0.middlewares: prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-longpolling-secure-0.rule:
        Host(`prueba.skoll.ar`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.prueba-15-0-prod-longpolling-secure-0.service: prueba-15-0-prod-longpolling
      traefik.http.routers.prueba-15-0-prod-longpolling-secure-0.middlewares: prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.prueba-15-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-0.rule:
        Host(`prueba.skoll.ar`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-0.service: prueba-15-0-prod-main
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-0.middlewares:
        prueba-15-0-prod-buffering, prueba-15-0-prod-compress,
        prueba-15-0-prod-forbid-crawlers, prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`prueba.skoll.ar`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-secure-0.service: prueba-15-0-prod-main
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-secure-0.middlewares:
        prueba-15-0-prod-buffering, prueba-15-0-prod-compress,
        prueba-15-0-prod-forbid-crawlers, prueba-15-0-prod-forceSecure
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.prueba-15-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.enable: "true"
      traefik.docker.network: "inverseproxy_shared"
      traefik.tcp.services.prueba-15-0-prod-database.loadbalancer.server.port: 5432
      traefik.prueba-15-0-prod-database-0.port: 5432
      traefik.tcp.routers.prueba-15-0-prod-database-0.rule: Host(`prueba.skoll.ar`)
      traefik.tcp.routers.prueba-15-0-prod-database-0.service: prueba-15-0-prod-database

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
